apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Deployment
  metadata:
    name: testclient
  spec:
    replicas: 1
    selector:
      app: testclient
    template:
      metadata:
        labels:
          app: testclient
      spec:
        containers:
          - image: confluentinc/cp-kafka:4.0.1-1
            command:
              - sh
              - -c
              - "exec tail -f /dev/null"